export default {
    ima:"I'm good in",
   firozsoftwaredevelopmentengineer:"Firoz Software Development Engineer",
    home:"Home",
    about:"About",
    services:"Services",
    skills:"Skills",
    contact:"Contact",
    projects:"Projects",
    resume:"Resume",
    comingSoon:"Coming Soon",
    unlockMyPotentialWithYou:"Bringing Simplicity And Reliability To Complex Software Challenges",
    github:"GitHub",
    githubCode:"GitHub Code",
    projectName:"Project Name",
    aboutProjects:"PROJECTS",
    highlight:"Highlights",
    techStacks:"Tech Stacks",
    html:"HTML",
    css:"CSS",
    reactNative:"React/Native",
    javaScript:"JavaScript",
    dsa:"DSA",
    git:"Git",
    sql:"SQL",
    c:"C",
    cpp:"C++",
    getInTouch:"get in touch",
    phone:"Phone",
    number:"8743010481",
    email:"Email",
    firozGmailCom:"firozkhandelhi62@gmail.com",
    address:"Address",
    newDelhi:"New Delhi",
    whyMe:"Why You should Hire Me?",
    introContent:"I have gained valuable experience from various internships and projects.      I excel at building websites that are easy for users to navigate and help businesses grow. My strength lies in designing the frontend of websites and solving problems creatively. I enjoy working in teams where I can share new ideas and tackle challenges effectively.",
    education:"Education",
    mDegree:"Master in Computer Science",
    bDegree:"Bachelor In Art",
    mUniversity:"Indira Gandhi National Open University",
    bUniversity:"School Of Open Learning Delhi University",
    mseason:"2019-2022",
    bseason:"2012-2016"
}